import './globals.scss';
import Header from '@/components/Header/Header';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { roboto, montserrat } from '@/font';
import { availableLocales } from '@/utils/i18n';
import AuthProvider from '@/components/auth-provider/AuthProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function generateStaticParams() {
  return availableLocales.map((local) => ({
    local,
  }));
}

export default function RootLayout({ children, params }) {
  const { local } = params;
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${montserrat.variable}`}>
        <Header local={local} />
        <main>
          <AuthProvider>{children}</AuthProvider>
        </main>
      </body>
    </html>
  );
}
